/**
 * Generated by tsnapi — public API snapshot of `ai-sdk-json-schema` */
// Interfaces
export interface ResolvedTextModelModule {
  role: string;
  specifier: string;
  resolvedPath: string;
  fileUrl: string;
  exportName: string;
}
export interface ResolveTextModelLoadPlanOptions {
  installationRoot?: string;
  env?: Record<string, string | undefined>;
  packageOptions?: unknown;
}
export interface TextModelConfig {
  provider: string;
  model: string;
}
export interface TextModelCreateBindingOperation {
  kind: 'create-binding';
  binding: string;
  moduleRole: string;
  options?: Record<string, unknown>;
}
export interface TextModelDescriptor extends TextModelConfig {
  providerName: string;
  providerDoc: string;
  env: readonly string[];
  catalogMatch: boolean;
  name: string;
  family?: string;
  attachment?: boolean;
  reasoning?: boolean;
  toolCall?: boolean;
  structuredOutput?: boolean;
  temperature?: boolean;
  knowledge?: string;
  releaseDate?: string;
  lastUpdated?: string;
  modalities?: {
    input: readonly string[];
    output: readonly string[];
  };
  packageName: string;
  api?: string;
  shape?: ModelShape;
}
export interface TextModelInvokeBindingOperation {
  kind: 'invoke-binding';
  binding: string;
  targetBinding: string;
  methodName?: string;
  args: TextModelLoadArgument[];
}
export interface TextModelLoadPlan {
  descriptor: TextModelDescriptor;
  adapterId: string;
  modules: ResolvedTextModelModule[];
  operations: TextModelLoadOperation[];
  resultBinding: string;
}

// Types
export type JsonSchemaObject = Record<string, unknown>;
export type TextModelLoadArgument = TextModelBindingArgument | TextModelValueArgument;
export type TextModelLoadOperation = TextModelCreateBindingOperation | TextModelInvokeBindingOperation;

// Classes
export declare class AdapterConfigurationError extends Error {
  readonly adapterId: string;
  constructor(adapterId: string, message: string);
}
export declare class InvalidProviderModuleError extends Error {
  readonly specifier: string;
  readonly resolvedPath: string;
  readonly exportName: string;
  constructor(args: {
    specifier: string;
    resolvedPath: string;
    exportName: string;
  });
}
export declare class MissingProviderPackageError extends Error {
  readonly packageName: string;
  readonly specifier: string;
  readonly installationRoot: string;
  constructor(args: {
    packageName: string;
    specifier: string;
    installationRoot: string;
    cause?: unknown;
  });
}
export declare class MissingTemplateVariableError extends Error {
  readonly variableName: string;
  readonly template: string;
  constructor(variableName: string, template: string);
}
export declare class UnknownModelError extends Error {
  readonly provider: string;
  readonly model: string;
  constructor(provider: string, model: string);
}
export declare class UnknownProviderError extends Error {
  readonly provider: string;
  constructor(provider: string);
}

// Functions
export declare function loadTextModel(_: unknown, _?: ResolveTextModelLoadPlanOptions): Promise<unknown>;
export declare function resolveTextModel(_: unknown): TextModelDescriptor;
export declare function resolveTextModelLoadPlan(_: unknown, _?: ResolveTextModelLoadPlanOptions): TextModelLoadPlan;

// Variables
export declare const generatedCatalog: GeneratedCatalog;
export declare const textModelConfigJsonSchema: JsonSchemaObject;
export declare const textModelConfigJsonSchemasByProvider: Record<string, JsonSchemaObject>;
export declare const textModelConfigSchema: z.ZodType<TextModelConfig>;
export declare const textModelConfigSchemasByProvider: Record<string, z.ZodType<TextModelConfig>>;