/**
 * Generated by tsnapi — public API snapshot of `ai-sdk-json-schema` */
// Interfaces
export interface BuildModelLoadPlanOptions {
  env?: Record<string, string | undefined>;
  packageOptions?: unknown;
}
export interface ExecuteResolvedModelLoadPlanOptions {
  loadModule?: (module: ResolvedModelModule) => Promise<Record<string, unknown>>;
}
export interface ExecuteUnresolvedModelLoadPlanOptions {
  loadModule: (module: ModelModulePlan) => Promise<Record<string, unknown>>;
}
export interface LoadModelOptions extends BuildModelLoadPlanOptions {
  installationRoot?: string;
}
export interface ModelBindingArgument {
  kind: 'binding';
  binding: string;
}
export interface ModelConfig {
  provider: string;
  model: string;
}
export interface ModelCreateBindingOperation {
  kind: 'create-binding';
  binding: string;
  moduleRole: string;
  options?: Record<string, unknown>;
}
export interface ModelDescriptor extends ModelConfig {
  mode: ModelMode;
  providerName: string;
  providerDoc: string;
  env: readonly string[];
  catalogMatch: boolean;
  name: string;
  supportedLoadModes: readonly ModelMode[];
  family?: string;
  attachment?: boolean;
  reasoning?: boolean;
  toolCall?: boolean;
  structuredOutput?: boolean;
  temperature?: boolean;
  knowledge?: string;
  releaseDate?: string;
  lastUpdated?: string;
  modalities?: {
    input: readonly string[];
    output: readonly string[];
  };
  packageName: string;
  api?: string;
  shape?: ModelShape;
}
export interface ModelInvokeBindingOperation {
  kind: 'invoke-binding';
  binding: string;
  targetBinding: string;
  methodName?: string;
  args: ModelLoadArgument[];
}
export interface ModelModulePlan {
  role: string;
  specifier: string;
  packageName: string;
  exportName: string;
}
export interface ResolvedModelLoadPlan {
  stage: 'resolved';
  mode: ModelMode;
  descriptor: ModelDescriptor;
  adapterId: string;
  modules: ResolvedModelModule[];
  operations: ModelLoadOperation[];
  resultBinding: string;
}
export interface ResolvedModelModule extends ModelModulePlan {
  resolvedPath: string;
  fileUrl: string;
}
export interface ResolveModelModulesOptions {
  installationRoot: string;
}
export interface UnresolvedModelLoadPlan {
  stage: 'unresolved';
  mode: ModelMode;
  descriptor: ModelDescriptor;
  adapterId: string;
  modules: ModelModulePlan[];
  operations: ModelLoadOperation[];
  resultBinding: string;
}

// Types
export type JsonSchemaObject = Record<string, unknown>;
export type ModelLoadArgument = ModelBindingArgument | ModelValueArgument;
export type ModelLoadOperation = ModelCreateBindingOperation | ModelInvokeBindingOperation;
export type ModelMode = SupportedLoadMode;

// Classes
export declare class AdapterConfigurationError extends Error {
  readonly adapterId: string;
  constructor(adapterId: string, message: string);
}
export declare class InvalidProviderModuleError extends Error {
  readonly specifier: string;
  readonly resolvedPath?: string;
  readonly exportName: string;
  constructor(args: {
    specifier: string;
    resolvedPath?: string;
    exportName: string;
  });
}
export declare class MissingProviderPackageError extends Error {
  readonly packageName: string;
  readonly specifier: string;
  readonly installationRoot: string;
  constructor(args: {
    packageName: string;
    specifier: string;
    installationRoot: string;
    cause?: unknown;
  });
}
export declare class MissingTemplateVariableError extends Error {
  readonly variableName: string;
  readonly template: string;
  constructor(variableName: string, template: string);
}
export declare class UnknownModelError extends Error {
  readonly provider: string;
  readonly model: string;
  constructor(provider: string, model: string);
}
export declare class UnknownProviderError extends Error {
  readonly provider: string;
  constructor(provider: string);
}

// Functions
export declare function buildModelLoadPlan(_: ModelMode, _: unknown, _?: BuildModelLoadPlanOptions): UnresolvedModelLoadPlan;
export declare function executeModelLoadPlan(_: ResolvedModelLoadPlan, _?: ExecuteResolvedModelLoadPlanOptions): Promise<unknown>;
export declare function loadTextModel(_: unknown, _?: LoadModelOptions): Promise<unknown>;
export declare function loadTranscriptionModel(_: unknown, _?: LoadModelOptions): Promise<unknown>;
export declare function resolveModel(_: ModelMode, _: unknown): ModelDescriptor;
export declare function resolveModelModules(_: UnresolvedModelLoadPlan, _: ResolveModelModulesOptions): ResolvedModelLoadPlan;

// Variables
export declare const textModelCatalog: GeneratedTextCatalog;
export declare const textModelConfigJsonSchema: JsonSchemaObject;
export declare const textModelConfigJsonSchemasByProvider: Record<string, JsonSchemaObject>;
export declare const textModelConfigSchema: z.ZodType<ModelConfig, unknown, z.core.$ZodTypeInternals<ModelConfig, unknown>>;
export declare const textModelConfigSchemasByProvider: Record<string, z.ZodType<ModelConfig, unknown, z.core.$ZodTypeInternals<ModelConfig, unknown>>>;
export declare const transcriptionModelCatalog: GeneratedTranscriptionCatalog;
export declare const transcriptionModelConfigJsonSchema: JsonSchemaObject;
export declare const transcriptionModelConfigJsonSchemasByProvider: Record<string, JsonSchemaObject>;
export declare const transcriptionModelConfigSchema: z.ZodType<ModelConfig, unknown, z.core.$ZodTypeInternals<ModelConfig, unknown>>;
export declare const transcriptionModelConfigSchemasByProvider: Record<string, z.ZodType<ModelConfig, unknown, z.core.$ZodTypeInternals<ModelConfig, unknown>>>;